### ISSUE TITLE
Not listing my TODOs

### ISSUE THREAD

**Issue by AuracleTech** [hxdyj/todo-highlighter#1]
![image](https://github.com/hxdyj/todo-highlighter/assets/40531871/946a01ad-47fe-44ff-b679-177e41b33be4)

OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
System Type	x64-based PC

**Comment by hxdyj** [comment]
> ![image](https://private-user-images.githubusercontent.com/40531871/331743084-946a01ad-47fe-44ff-b679-177e41b33be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjA4NjMsIm5iZiI6MTcxNjAyMDU2MywicGF0aCI6Ii80MDUzMTg3MS8zMzE3NDMwODQtOTQ2YTAxYWQtNDdmZS00NGZmLWI2NzktMTc3ZTQxYjMzYmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA4MjI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYzc1NjBlYjNhZTg1MWRjNDAwMmFlYjZiYjg0NjFiOWI5MzliOTcyZDJhM2M4ODYwZTc1YWJjMDMyNDA5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6zloe4aKqYv6cYOFL2VuCEdYjfb8J30a1Z02A6eKr5E)
> 
> OS Name Microsoft Windows 11 Pro Version 10.0.22631 Build 22631 System Type x64-based PC

You can config in vscode settings, add rs file
![image](https://github.com/hxdyj/todo-highlighter/assets/14368755/b8ef56c7-e269-44ea-a8b8-f7cb3bfcf230)

**Comment by AuracleTech** [comment]
It would be nice if they would all be enabled by default
Many people probably uninstalled it too because of this

**Comment by hxdyj** [comment]
> It would be nice if they would all be enabled by default
> Many people probably uninstalled it too because of this

Thank u for your suggestion, I will optimize       
this later.

**Comment by hxdyj** [comment]
done, update to v1.0.8
